### ISSUE TITLE
Doesn't work with accentuated strings

### ISSUE THREAD

**Issue by Awea** [Mayeu/slugify#9]
Hi :)

I wanted to use this script to slugify some strings but it doesn't work with accentuated string, for example:

```bash
➜ slugify "éeé"
-e
```

**Comment by Mayeu** [comment]
Yo 👋 
Can you add a test case in a PR highlighting this issue?

**Comment by Awea** [comment]
Sure thing :)

**Comment by Mayeu** [comment]
Ha I see what you mean now :)

That's actually impossible to do with POSIX sh beside maintaining a whole conversion table manually (which I don't plan to do ^^).

I previously tried to do this via the `iconv` tool, but it's not portable because it relies on GNU specific features that are not available in POSIX iconv 🙁 

I started a [go version of the script](https://github.com/Mayeu/slugify/pull/7), which may end up in a different project instead of replacing this one.

So, sorry, but that's going to be a won't fix 😢

**Comment by Awea** [comment]
So sad to read that in 2020 there is no universal solution to deal with accentuated strings :(

Thanks for your explanations :3
